export const gone410ExactPaths = [
  '/modules.php',
  '/h2n.php',
  '/undefined',
  '/blog/amniyon-sivisinin-azligi-da-coklugu-da-bebek-icin-tehlike-isareti',
  '/blog/bebegin-gec-dogmasi-surmaturite-gun-asimi',
  '/blog/bebegin-suyu-erken-gelirse-erken-membran-rupturu-emr',
  '/blog/bebegin-suyu-fazla-ise',
  '/blog/dogum-sonrasi-vucudumuzda-neler-oluyor',
  '/blog/hamilelikte-hepatit-sarilik-ve-tedavisi',
  '/blog/hamilelikte-kabizlik-basurlar-hemoroidler-ve-makat-catlaklari',
  '/blog/hamilelikte-kabizlik-tehlikeli-midir',
  '/blog/hamilelikte-tehlikeli-bir-enfeksiyon-sitomegalovirus',
  '/blog/hamilelikte-yuksek-tansiyon-problemi-olan-anne-adaylari-nelere-dikkat-etmeli',
  '/blog/plasentanin-erken-ayrilmasi-dekolman-plasenta',
  '/blog/plasentanin-onde-olmasi-plasenta-previa',
];

export const routeAliases = {
  '/ar/blog/azoospermia-and-micro-tese': '/makaleler/azospermi-mikro-tese',
  '/ar/blog/bleeding-after-embryo-transfer': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/ar/blog/endometriosis-infertility-ivf-surgery-2025': '/makaleler/endometriozis-tup-bebek',
  '/ar/blog/embryo-grading-4aa-3bb-5bc-decoding-ivf-lab-report': '/makaleler/laboratuvar-raporu-yorumlama',
  '/ar/blog/endometrial-scratching-ivf': '/makaleler/endometriyal-scratching',
  '/ar/blog/hysteroscopy-before-ivf-necessity-recommendations': '/makaleler/ivf-oncesi-histeroskopi',
  '/ar/blog/immunological-treatments-ivf-implantation-failure': '/makaleler/bagisiklik-tedavileri',
  '/ar/blog/isotretinoin-for-azoospermia': '/makaleler/izotretinoin-sperm',
  '/ar/blog/vaginal-microbiome-ivf-success-lactobacillus-crispatus': '/makaleler/vajinal-mikrobiyom-fiv',
  '/ar/about-us': '/hakkimizda',
  '/ar/contact-us': '/iletisim',
  '/ar/health-visa': '/tani-sureci',
  '/ar/ivf-explained': '/ivf-rehberi',
  '/ar/ivf-in-turkey': '/',
  '/ar/services': '/tedavi-yontemleri',
  '/ar/step-by-step-ivf-process': '/ivf-rehberi',
  '/ar/success-rates': '/basari-oranlari',
  '/ar/treatment': '/tedavi-yontemleri',
  '/ar/treatment/causes-and-diagnosis-of-infertility': '/tedavi-yontemleri',
  '/ar/treatment/embryo-freezing': '/makaleler/taze-dondurulmus-transfer',
  '/ar/treatment/stimulation-of-the-ovaries': '/makaleler/ivf-protokolleri',
  '/ar/before-you-come': '/tani-sureci',
  '/ar/dr-senai-aksoy': '/hakkimizda',
  '/ar': '/',
  '/$%7BsafeUrl%7D': '/',
  '/$%7Bresult.url%7D': '/',
  '/$%7Burl%7D': '/',
  '/${safeUrl}': '/',
  '/${result.url}': '/',
  '/${url}': '/',
  '/aciklanamayan-kisirlik': '/aciklanamayan-infertilite',
  '/about-us': '/hakkimizda',
  // '/asilama' is handled by public/_redirects (→ /makaleler/iui-nedir/).
  // Removed conflicting alias that pointed to /tedavi-yontemleri#iui.
  '/before-you-come': '/tani-sureci',
  '/baslarken': '/ivf-rehberi',
  '/blog': '/makaleler',
  '/blog/': '/makaleler',
  '/blog/azoospermia-and-micro-tese': '/makaleler/azospermi-mikro-tese',
  '/blog/bleeding-after-embryo-transfer': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/can-preimplantation-genetic-testing-be-used-for-sex-selection': '/makaleler/pgt-cinsiyet-secimi',
  '/blog/candidates-for-hysteroscopy': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/care-after-embryo-transfer-with-ivf': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/chronic-endometritis-and-ivf': '/makaleler/endometriozis-tup-bebek',
  '/blog/decoding-the-beta-hcg-test-results-for-ivf-patients': '/makaleler/beta-hcg-testi',
  '/blog/discharge-itching-odor-yeast-infection-or-bacterial-vaginosis': '/makaleler/akinti-kasinti-koku',
  '/blog/embryo-transfer-ivf-treatment': '/makaleler/embriyo-transferi-gun-secimi',
  '/blog/endometrial-scratching-ivf': '/makaleler/endometriyal-scratching',
  '/blog/endometriosis-diagnosis-2025': '/makaleler/endometriozis-akilli-stratejiler',
  '/blog/elevating-ivf-journey-the-chic-guide': '/makaleler/tup-bebek-sureci-rehber',
  '/blog/exploring-the-role-of-female-infertility-in-ivf-treatment': '/kadin-infertilitesi',
  '/blog/frozen-embryo-transfer-endometrial-preparation-protocols-hrt-natural-hybrid': '/makaleler/taze-dondurulmus-transfer',
  '/blog/guide-complete-freezing-oocytes': '/makaleler/yumurta-dondurma-rehberi',
  '/blog/how-many-eggs-for-ivf-success': '/makaleler/kac-yumurta-gerekir',
  '/blog/hydrosalpinx-and-infertility': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/hysteroscopy-female-infertility-evidence-guide': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/isotretinoin-for-azoospermia': '/makaleler/izotretinoin-sperm',
  '/blog/ivf-as-an-option-for-women-with-ovulation-disorders': '/makaleler/opk-ve-ivf',
  '/blog/ivf-protocols-medications': '/makaleler/ivf-protokolleri',
  '/blog/in-vitro-fertilization-treatment-and-polycystic-ovary-syndrome': '/makaleler/opk-ve-ivf',
  '/blog/male-infertility-supplements-comprehensive-guide': '/makaleler/erkek-dogurganlik-besin-takviyeleri',
  '/blog/ovarian-prp': '/makaleler/over-prp',
  '/blog/pcos-and-ivf': '/makaleler/opk-ve-ivf',
  '/blog/preimplantation-genetic-diagnosis-of-monogenic-diseases': '/makaleler/pgt-m',
  '/blog/research-into-the-relationship-between-hyperprolactinemia-and-milk-secretion': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/the-use-of-frozen-embryos-in-ivf-treatment': '/makaleler/taze-dondurulmus-transfer',
  '/blog/understanding-the-reproductive-potential-of-ivf': '/makaleler/tup-bebek-nedir',
  '/blog/understanding-unexplained-infertility-guide-for-couples': '/makaleler/aciklanamayan-infertilite',
  '/blog/understanding-uterine-fibroids-and-infertility': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/unraveling-the-complexities-of-hyperprolactinemia': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/dogurganligin-korunmasi': '/fertilite-koruma',
  '/dr-senai-aksoy': '/hakkimizda',
  '/dr-senai-aksoy/undefined/dr-senai-aksoy': '/hakkimizda',
  // '/embriyo-dondurma' is handled by public/_redirects (→ /makaleler/taze-dondurulmus-transfer/).
  // Removed conflicting alias that pointed to /fertilite-koruma.
  '/hizmetler': '/tedavi-yontemleri',
  '/health-visa': '/tani-sureci',
  '/erkegin-degerlendirilmesi': '/erkek-infertilitesi',
  '/fr': '/',
  '/fr/a-propos-de-nous': '/hakkimizda',
  '/fr/before-you-come': '/tani-sureci',
  '/fr/contact-us': '/iletisim',
  '/fr/cout-de-la-fiv': '/sss',
  '/fr/dr-senai-aksoy': '/hakkimizda',
  '/fr/ivf-in-turkey': '/',
  '/fr/la-fiv-etape-par-etape': '/ivf-rehberi',
  '/fr/taux-de-reussite': '/basari-oranlari',
  '/fr/traitement': '/tedavi-yontemleri',
  '/fr/traitement/ai-je-besoin-d-un-traitement': '/tedavi-yontemleri',
  '/fr/traitement/ponction-ovocytaire': '/makaleler/ivf-protokolleri',
  '/fr/traitement/tests-pre-fiv': '/tani-sureci',
  '/fr/traitement/transfert-d-embryon': '/makaleler/embriyo-transferi-gun-secimi',
  '/fr/blog': '/makaleler',
  '/fr/blog/adenomyose-et-infertilite': '/makaleler/hormonal-tedavi-adenomyozis',
  '/fr/blog/azoospermie-microtese': '/makaleler/azospermi-mikro-tese',
  '/fr/blog/echec-fiv-que-faire-dr-senai-aksoy': '/makaleler/basarisiz-denemeler',
  '/fr/blog/fiv-et-limite-dage-le-point-de-vue-dun-medecin': '/yas-ve-fertilite',
  '/fr/blog/fiv-turquie-securite-qualite-couts': '/makaleler/iyi-tup-bebek-merkezi',
  '/fr/blog/frozen-embryo-transfer-endometrial-preparation-protocols-hrt-natural-hybrid': '/makaleler/taze-dondurulmus-transfer',
  '/fr/blog/grossesse-naturelle-apres-fiv-surprise-fertilite': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/fr/blog/diagnostic-preimplantatoire-des-maladies-monogeniques': '/makaleler/pgt-m',
  '/fr/blog/diagnostic-preimplantatoire-et-selection-du-sexe': '/makaleler/pgt-cinsiyet-secimi',
  '/fr/blog/embryoglue-fiv-efficacite-taux-reussite': '/makaleler/embryoglue-faydalari',
  '/fr/blog/endometrite-chronique-et-fiv': '/makaleler/endometriozis-tup-bebek',
  '/fr/blog/guide-complet-congelation-ovocytes': '/makaleler/yumurta-dondurma-rehberi',
  '/fr/blog/hydrosalpinx-et-infertilite': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/fr/blog/hyperprolactinemie-et-infertilite': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/fr/blog/hysteroscopie-avant-fiv-necessite-recommandations': '/makaleler/ivf-oncesi-histeroskopi',
  '/fr/blog/comprendre-infertilite-en-fiv': '/makaleler/tup-bebek-nedir',
  '/fr/blog/infertilite-inexpliquee': '/makaleler/aciklanamayan-infertilite',
  '/fr/blog/isotretinoine-restauration-spermatogenese-noa': '/makaleler/izotretinoin-sperm',
  '/fr/blog/le-prp-ovarien': '/makaleler/over-prp',
  '/fr/blog/microbiote-vaginal-et-succes-fiv': '/makaleler/vajinal-mikrobiyom-fiv',
  '/fr/blog/moment-optimal-pour-le-transfert-embryons': '/makaleler/embriyo-transferi-gun-secimi',
  '/fr/blog/myomectomie-coelioscopie-limites-fertilite': '/makaleler/miyom-ameliyati',
  '/fr/blog/pcos-et-fiv': '/makaleler/opk-ve-ivf',
  '/fr/blog/risques-caches-des-grossesses-gemellaires-en-fiv': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/fr/blog/soins-post-transfert-embryons': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/fr/blog/treatment-pain-associated-endometriosis': '/makaleler/endometriozis-akilli-stratejiler',
  '/fr/blog/traitements-chirurgicaux-douleur-endometriose': '/makaleler/endometriozis-akilli-stratejiler',
  '/fr/blog/transfert-embryons-dans-le-traitement-de-la-fiv': '/makaleler/embriyo-transferi-gun-secimi',
  '/histeroskopi': '/makaleler/ivf-oncesi-histeroskopi',
  // '/laparoskopi' is handled by public/_redirects (→ /makaleler/endoskopik-cerrahi-histeroskopi/).
  // Removed conflicting alias that pointed to /endometriozis-adenomyozis.
  '/cost-of-ivf': '/sss',
  '/fr/cost-of-ivf': '/sss',
  '/kadinda-kisirlik-nedenleri': '/kadin-infertilitesi',
  '/kisirlik-nedenleri/aciklanamayan-kisirlik': '/aciklanamayan-infertilite',
  '/kvkk': '/gizlilik-politikasi',
  '/makaleler/dondurulmus-embriyo-transferi': '/makaleler/taze-dondurulmus-transfer',
  '/makaleler/bilimsel-makaleler/tup-bebek-tedavisinde-bos-folikul-sendromu': '/makaleler/ivf-protokolleri',
  '/makaleler/dusuk-amh-': '/makaleler/dusuk-amh-hamilelik',
  '/makaleler/embryoscope-': '/makaleler/embryoscope-yapay-zeka',
  '/makaleler/erkek-kisirligi-besin-takviyeleri': '/makaleler/erkek-dogurganlik-besin-takviyeleri',
  '/makaleler/hiperprolaktinemi-prolaktinom': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/makaleler/hamilelik-ve-dogum': '/makaleler',
  '/makaleler/myomlar-ve-kisirlik': '/makaleler/miyomlar-ve-tup-bebek',
  '/makaleler/kisirlik/polikistik-over-sendromu-nedenleri-ve-tedavisi': '/makaleler/opk-ve-ivf',
  '/makaleler/kisirlik/polip-nedir-kisirliga-yol-acar-mi': '/makaleler/miyomlar-ve-tup-bebek',
  '/makaleler/kisirlik/yumurtalik-donmesi-over-torsiyonu': '/makaleler/endometrioma',
  '/makaleler/tup-bebek/embriyo-transferi-kacinci-gunde-yapilmalidir': '/makaleler/embriyo-transferi-gun-secimi',
  '/makaleler/tup-bebek/tup-bebek-nedir-kimlere-uygulanir': '/makaleler/tup-bebek-nedir',
  '/makaleler/tup-bebek/tup-bebek-tedavisinde-yumurtalik-hiperstimulasyon-sendromu-ohss': '/makaleler/ivf-protokolleri',
  '/makaleler/pkos-ve-tup-bebek': '/makaleler/opk-ve-ivf',
  '/policy': '/gizlilik-politikasi',
  // '/public/*' handled by Worker as 410 Gone (GONE_410_PREFIXES).
  // '/modules.php' and '/h2n.php' return 410 Gone via [...legacy].ts.
  // Removed 301 aliases to prevent the Worker from redirecting before
  // GONE_410_EXACT check (it's checked first anyway, but cleaner).
  '/services': '/tedavi-yontemleri',
  '/contact-us': '/iletisim',
  '/ivf-explained': '/ivf-rehberi',
  '/ivf-in-turkey': '/',
  '/randevu': '/iletisim',
  '/success-rates': '/basari-oranlari',
  '/step-by-step-ivf-process': '/ivf-rehberi',
  '/treatment': '/tedavi-yontemleri',
  '/treatment/fertilization-ivf-and-icsi': '/makaleler/ivf-protokolleri',
  '/treatment/causes-and-diagnosis-of-infertility': '/tedavi-yontemleri',
  '/treatment/do-i-need-treatment': '/tedavi-yontemleri',
  '/treatment/embryo-freezing': '/makaleler/taze-dondurulmus-transfer',
  '/treatment/embryo-transfer': '/makaleler/embriyo-transferi-gun-secimi',
  '/treatment/egg-retrieval': '/tedavi-yontemleri',
  '/treatment/faq': '/sss',
  '/treatment/pre-ivf-testing': '/tani-sureci',
  '/treatment/preimplantation-genetic-diagnosis': '/pgt-merkezi',
  '/treatment/reasons-for-cancellation-of-treatment': '/tedavi-yontemleri',
  '/treatment/sperm-retrieval-in-azoospermic-subjects': '/makaleler/cerrahi-sperm-arama-tese',
  '/treatment/stimulation-of-the-ovaries': '/makaleler/ivf-protokolleri',
  '/sik-sorulan-sorular': '/sss',
  '/tedavi-sureci': '/tedavi-yontemleri',
  '/tedavi-sirasinda-karsilasilan-sorunlar': '/ivf-rehberi',
  '/tedaviler': '/tedavi-yontemleri',
  '/tedaviniz': '/ivf-rehberi',
  '/tedaviye-baslamadan-once': '/tani-sureci',
  '/tesatese': '/makaleler/azospermi-mikro-tese',
  // '/tup-bebek-asamalari' is handled by public/_redirects (→ /ivf-rehberi/).
  // Removed conflicting alias that pointed to /transfer-sureci.
  '/tup-bebek-basari-oranlari': '/basari-oranlari',
  '/tup-bebek-evraklari-ve-testleri': '/tani-sureci',
  '/tup-bebek-fiyatlari': '/sss',
  '/tup-bebek-tedavisinde-catlatma-ignesi': '/makaleler/ivf-protokolleri',
  '/tup-bebek-tedavisinde-nelere-dikkat-etmelisiniz': '/makaleler/tup-bebek-sureci-rehber',
  '/tup-bebek-tedavisinde-preimplantasyon-genetik-tani': '/pgt-merkezi',
  '/tup-bebek-ve-mikroenjeksiyon': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/tup-bebekte-ozel-uygulamalar': '/tedavi-yontemleri',
  '/tup-bebek-tedavim-tuttu-mu': '/basari-oranlari',
  '/tedavideki-hastalar/yumurta-toplanamamasi': '/makaleler/ivf-protokolleri',
  '/videolar/cikolata-kisti-nedir': '/makaleler/endometrioma',
  '/videolar/mikroenjeksiyon-yontemi-hangi-durumlarda-uygulanir': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/videolar/tup-bebek-tedavisi-nedir-animasyon': '/ivf-rehberi',
  '/videolar/tup-bebek-tedavisi-yumurta-takibi': '/makaleler/ivf-protokolleri',
  '/videolar/tup-bebek/tup-bebek-tedavisi-ve-tup-bebek-asamalari': '/ivf-rehberi',
  '/videolar/rahim-ici-yapisikliklarinda-ofis-histeroskopi': '/makaleler/ivf-oncesi-histeroskopi',
  '/yasiniz-ve-kisirlik': '/yas-ve-fertilite',
  '/yumurtaliklarin-asiri-uyarilmasi': '/makaleler/ivf-protokolleri',
  '/yumurtlama-takibi': '/makaleler/yumurtlama-takibi',
  '/yazar': '/yayin-kurulu',
  '/blog/akinti-kasinti-koku-mantar-mi-bakteriyel-vajinoz-mu': '/makaleler/akinti-kasinti-koku',
  '/blog/tup-bebek-bagisiklik-tedavileri-ve-riskler': '/makaleler/bagisiklik-tedavileri',
  '/blog/ivf-oncesi-histeroskopi-rif-hastalari': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/embryoscope-yapay-zeka-embriyo-secimi': '/makaleler/embryoscope-yapay-zeka',
  '/blog/yumurta-dondurma-kac-tanesi-gerekli-yas-gruplari': '/makaleler/yumurta-dondurma-rehberi',
  '/blog/izotretinoin-noa-sperm-uretimi': '/makaleler/izotretinoin-sperm',
  '/blog/embriyo-tup-bebek-laboratuvar-raporu-yorumlama': '/makaleler/laboratuvar-raporu-yorumlama',
  '/blog/istanbul-tup-bebek-doktoru-merkezi-secimi-rehberi': '/makaleler/istanbul-tup-bebek-doktoru',
  '/blog/akraba-evliligi-neden-tehlikelidir': '/makaleler/akraba-evliligi',
  '/blog/embriyo-transferi-kacinci-gunde-yapilmalidir': '/makaleler/embriyo-transferi-gun-secimi',
  '/blog/dondurulmus-embriyo-transferi-protokolleri-karsilastirma': '/makaleler/taze-dondurulmus-transfer',
  '/blog/vajinal-mikrobiyom-fiv-basarisi': '/makaleler/vajinal-mikrobiyom-fiv',
  '/blog/endometriozis-ve-tup-bebek-tedavisi': '/makaleler/endometriozis-tup-bebek',
  '/blog/endometriozis-kisirlik-iliskisi': '/makaleler/endometriozis-tup-bebek',
  '/blog/kisirlik-ve-endometriozis-icin-akilli-stratejiler': '/makaleler/endometriozis-akilli-stratejiler',
  '/blog/azospermi-mikro-tese-ikinci-deneme': '/makaleler/azospermi-mikro-tese',
  '/blog/azospermi-nedir': '/makaleler/cerrahi-sperm-arama-tese',
  '/blog/tup-bebekte-basarili-sonuc-icin-kac-yumurta-gerekir': '/makaleler/kac-yumurta-gerekir',
  '/blog/yumurtlama-takibi-ve-iliski-planlamasi-nedir': '/makaleler/yumurtlama-takibi',
  '/blog/saglikli-bir-cinsel-hayat-icin-ne-yapmali': '/beslenme-yasam',
  '/blog/taze-dondurulmus-embriyo-transferi': '/makaleler/taze-dondurulmus-transfer',
  '/blog/miyom-ameliyati-ne-zaman-gerekir': '/makaleler/miyom-ameliyati',
  '/blog/miyomlarin-gebelik-uzerinde-etkileri-nelerdir': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/myomektomi-myom-nedir': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/laparoskopik-myomektomi': '/makaleler/miyom-ameliyati',
  '/blog/dusuk-amh': '/makaleler/dusuk-amh-hamilelik',
  '/blog/zayif-yumurtalik-rezervi-ve-tup-bebek-tedavisi': '/makaleler/dusuk-amh-hamilelik',
  '/blog/prematur-ovarian-yetmezlik-kisirlik-nedeni': '/makaleler/dusuk-amh-hamilelik',
  '/blog/erken-yumurtalik-yetmezligi-kisirlik-nedeni': '/makaleler/dusuk-amh-hamilelik',
  '/blog/erken-menopoz-nedir': '/makaleler/dusuk-amh-hamilelik',
  '/blog/fiv-basarisizligi-sonrasi-ne-yapmali-dr-senai-aksoy': '/makaleler/basarisiz-denemeler',
  '/blog/tekrarlayan-dusuklerin-nedenleri': '/makaleler/basarisiz-denemeler',
  '/blog/tup-bebek-tedavisinde-tekrarlayan-basarisizliklar': '/makaleler/basarisiz-denemeler',
  '/blog/luteal-faz-defekti-kisirlik-nedeni': '/makaleler/basarisiz-denemeler',
  '/blog/ivf-protokolleri-istanbul': '/makaleler/ivf-protokolleri',
  '/blog/hiperprolaktinemi-ve-kisirlik': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/hiperprolaktinemi-ve-prolaktinomu-anlamak': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/gogusten-sivi-gelmesi-galaktore-nedir': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/asiri-sut-uretimi-hiperprolaktinemi': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/miyomlar-ve-tup-bebek': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/myomlar-ve-kisirlik': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/kimyasal-gebelik': '/makaleler/kimyasal-gebelik',
  '/blog/bos-gebelik-nedir': '/makaleler/kimyasal-gebelik',
  '/blog/hamile-kalamiyorsaniz-nedeni-hidrosalpinks-olabilir': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/hidrosalpinks-ve-tuplerin-alinmasi': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/hydrosalpinx-ve-kisirlik': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/pelvik-inflamatuar-hastalik-pid-kisirlik-nedeni-olabilir': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/tuboovarian-abse-toa': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/embriyo-tutunmasi-implantasyon-1-rahime-ait-problemler': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/embriyo-tutunmasi-implantasyon-2-embriyoya-ait-problemler': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/embriyo-tutunmasi-implantasyon-3-tup-bebek-asamalarinda-yapilabilecekler': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/tup-bebek-ve-embriyo-transferi-sonrasi-bakim': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/tup-bebek-tedavisinde-luteal-faz-kanamalari': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/tup-bebek-tedavisinde-blastokist-transferi-nedir': '/makaleler/embriyo-transferi-gun-secimi',
  '/blog/kisirlik-cozumsuz-degildir1-yazi-dizisi-kadinda-kisirlik-nedenleri': '/kadin-infertilitesi',
  '/blog/kisirlik-cozumsuz-degildir2-yazi-dizisi-kadinda-tup-bebek-tedavisi': '/makaleler/tup-bebek-nedir',
  '/blog/kisirlik-cozumsuz-degildir2-yazi-dizisi-erkekte-baslica-kisirlik-nedenleri': '/erkek-infertilitesi',
  '/blog/kisirlik-cozumsuz-degildir4-yazi-dizisi-azospermi-cerrahi-sperm-arama-teknikleri': '/makaleler/cerrahi-sperm-arama-tese',
  '/blog/erkekte-kisirlik-tedavisinde-cerrahi-sperm-arama-tesa-tese': '/makaleler/cerrahi-sperm-arama-tese',
  '/blog/kisirlik-cozumsuz-degildir3-yazi-dizisi-erkekte-kisirlik-nasil-degerlendirilir': '/erkek-infertilitesi',
  '/blog/erkekte-kisirlik-nedeni-varikosel-nedir': '/erkek-infertilitesi',
  '/blog/tup-bebek-tedavisi-esnasinda-semen-analizi-nedir': '/erkek-infertilitesi',
  '/blog/erkek-dogurganligini-artiran-besin-takviyeleri': '/makaleler/erkek-dogurganlik-besin-takviyeleri',
  '/blog/tup-bebek-artik-pek-cok-durumda-oncelikli-tedavi-yontemi': '/makaleler/tup-bebek-nedir',
  '/blog/tup-bebek-nedir-kimlere-uygulanir': '/makaleler/tup-bebek-nedir',
  '/blog/pek-cok-kisir-ciftin-hayatini-degistiren-mucize-tup-bebek': '/makaleler/tup-bebek-nedir',
  '/blog/tup-bebek-tedavisinde-tartismali-teknik-kokultur-yapay-rahim': '/makaleler/tup-bebek-nedir',
  '/blog/tup-bebek-tedavisine-hazirlik-asamasi-yazi-dizisi-1': '/makaleler/tup-bebek-sureci-rehber',
  '/blog/iyi-tup-bebek-merkezi-nasil-anlasilir': '/makaleler/iyi-tup-bebek-merkezi',
  '/blog/mikroenjeksiyonda-imsi-nedir': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/blog/mikroenjeksiyon-icsi-nedir-kimlere-uygulanir': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/blog/beta-hcg-test-sonuclari': '/makaleler/beta-hcg-testi',
  '/blog/yumurtalik-kistleri-dermoid-kist': '/makaleler/yumurtalik-kistleri-dogurganlik',
  '/blog/endometrioma': '/makaleler/endometrioma',
  '/blog/over-prp': '/makaleler/over-prp',
  '/blog/pgt-m': '/makaleler/pgt-m',
  '/blog/preimplantasyon-genetik-testi-ve-cinsiyet-secimi': '/makaleler/pgt-cinsiyet-secimi',
  '/blog/embriyoda-genetik-tani-preimplantasyon-genetik-tani': '/pgt-merkezi',
  '/blog/embryoglue-embriyo-yapistiricisi-faydalari': '/makaleler/embryoglue-faydalari',
  '/blog/pkos-ve-tup-bebek': '/makaleler/opk-ve-ivf',
  '/blog/polikistik-over-sendromu-nedenleri-ve-tedavisi': '/makaleler/opk-ve-ivf',
  '/blog/adet-duzensizligi-ve-polikistik-over-sendromu-pkos': '/makaleler/adet-duzensizligi-pcos',
  '/blog/adet-oncesi-sendromu': '/makaleler/adet-duzensizligi-pcos',
  '/blog/adet-gorememe-amenore': '/makaleler/adet-gorememe',
  '/blog/alkol-ve-fertilite': '/makaleler/alkol-ve-fertilite',
  '/blog/hormonal-tedavilerle-adenomyozis': '/makaleler/hormonal-tedavi-adenomyozis',
  '/blog/hysteroscopic-cytoreductive-surgery-for-adenomyosis': '/makaleler/hormonal-tedavi-adenomyozis',
  '/blog/asherman-sendromu-rahim-ici-yapisiklik': '/makaleler/asherman-sendromu',
  '/blog/embriyo-dondurma-teknigi-vitrifikasyon': '/makaleler/taze-dondurulmus-transfer',
  '/blog/assisted-hatching-destekli-yuvalama-nedir': '/makaleler/ivf-protokolleri',
  '/blog/tup-bebek-tedavisinde-yumurta-toplamanin-gecikmesi': '/makaleler/ivf-protokolleri',
  '/blog/yumurta-toplamada-genel-anestezi-mi-sedasyon-mu': '/makaleler/ivf-protokolleri',
  '/blog/tup-bebek-tedavisinde-yumurtalik-hiperstimulasyon-sendromu-ohss': '/makaleler/ivf-protokolleri',
  '/blog/tup-bebek-tedavisinde-bos-folikul-sendromu': '/makaleler/ivf-protokolleri',
  '/blog/hlag-ne-kadar-yararli': '/makaleler/ivf-protokolleri',
  '/blog/ofis-histeroskopi-nedir': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/intrauterin-inseminasyon-iui-nedir': '/makaleler/iui-nedir',
  '/blog/immunological-treatments-ivf-implantation-failure': '/makaleler/bagisiklik-tedavileri',
  '/blog/yumurtalik-donmesi-over-torsiyonu': '/makaleler/endometrioma',
  '/blog/cikolata-kisti-endometriozis-ameliyati-yumurtalik-veya-rahmin-alinmasini-gerektirmez': '/makaleler/endometrioma',
  '/blog/klamidya-kisirliga-neden-olabilir': '/makaleler/akinti-kasinti-koku',
  '/blog/vajinit-vajinal-enfeksiyon-ve-vajinal-akinti': '/makaleler/akinti-kasinti-koku',
  '/blog/bel-sogukluguna-kadinlar-da-yakalanabilir': '/makaleler/akinti-kasinti-koku',
  '/blog/hamilelikte-sik-gorulen-vajinal-enfeksiyonlar': '/makaleler/akinti-kasinti-koku',
  '/blog/tup-bebek-ve-kisirlik-hakkinda-yanlis-bilinen-gercekler': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/blog/tup-bebekte-kullanilan-kanita-dayali-olmayan-tedaviler': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/blog/kanser-tedavisine-bagli-kisirlik-ve-dogurganligin-korunmasi': '/makaleler/kanser-ve-fertilite',
  '/blog/stres-tup-bebek-basarisini-etkiler-mi': '/psikolojik-destek',
  '/blog/stres-ve-kisirlik': '/psikolojik-destek',
  '/blog/sigara-ve-kisirlik': '/beslenme-yasam',
  '/blog/sigaranin-dogurganlik-ve-kisirlik-uzerinde-etkisi': '/beslenme-yasam',
  '/blog/dogurganligi-arttirmanin-10-yolu': '/beslenme-yasam',
  '/blog/gebelikte-cinsel-yasam': '/beslenme-yasam',
  '/blog/hamilelik-ve-flor': '/beslenme-yasam',
  '/blog/hamilelik-ve-alkol': '/beslenme-yasam',
  '/blog/hamilelerde-tiroid-hastaliklari': '/hormon-paneli',
  '/blog/anne-karninda-tarama-testleri': '/genetik-testler',
  '/blog/ilacli-rahim-filmi-hsg-nedir': '/tani-sureci',
  '/blog/dogumsal-rahim-anomalileri-konjenital-uterin-anomalileri': '/kadin-infertilitesi',
  '/blog/dogustan-rahmin-olmamasi-mullerian-agnenezi-rokitansky-kuster-hauser-mayer-sendromu-rkm': '/kadin-infertilitesi',
  '/blog/kisirlik-infertilite-nedir-nedenleri-nelerdir': '/kadin-infertilitesi',
  '/blog/embriyo-transferi-kacinci-': '/makaleler/embriyo-transferi-gun-secimi',
  '/blog/embriyo-transferi-sonrasi-kanama': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/does-embryoglue-increase-ivf-success': '/makaleler/embryoglue-faydalari',
  '/blog/hamilelikte-sigara-icmek-olu-dogum-oranini-artiyor': '/beslenme-yasam',
  '/blog/hysteroscopy-before-ivf-necessity-recommendations': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/yumurta-dondurma-kac-tanesi-gerekli-ya%C5%9F-gruplar%C4%B1': '/makaleler/yumurta-dondurma-rehberi',
  '/embriyo-tup-bebek-laboratuvar-raporu-yorumlama': '/makaleler/laboratuvar-raporu-yorumlama',
  // '/blog/sayfa/N/' pagination handled by Worker as 410 Gone (GONE_410_PREFIXES).
  // (the '*' glob key here never matched — exact-string lookup, not pattern).

  // === 2026-07-06: 50 missing blog slug aliases (GSC redirect drilldown) ===
  '/blog/cep-telefonları-ve-sperm kalitesi': '/makaleler/cep-telefonu-sperm-kalitesi',
  '/blog/cogul-gebelikler-ve-riskleri': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/blog/dis-gebelik-nedir': '/makaleler/beta-hcg-testi#ektopik',
  '/blog/dogurganlikbeslenme-iliskisi': '/beslenme-yasam',
  '/blog/dusuk-abortus-nedir': '/makaleler/dusuk-sonrasi-hamilelik-bekleme-suresi#neden-olur',
  '/blog/dusuk-amh-hamilelik-sansi': '/makaleler/dusuk-amh-hamilelik',
  '/blog/endometriyal_scratching_ivf': '/makaleler/endometriyal-scratching',
  '/blog/endoskopik-cerrahi-histeroskopi-nedir': '/makaleler/endoskopik-cerrahi-histeroskopi',
  '/blog/erkek-kisirligi-besin-takviyeleri': '/makaleler/erkek-dogurganlik-besin-takviyeleri',
  '/blog/erkekte-kisirlik-nedenleri': '/erkek-infertilitesi',
  '/blog/hamilelikte-aspirin-ve-progesteron': '/makaleler/ivf-protokolleri',
  '/blog/ilacsiz-tup-bebek-ivm-yontemi-ne-kadar-basarili': '/makaleler/ivf-protokolleri',
  '/blog/izsiz-ameliyat-laparoskopi': '/makaleler/endoskopik-cerrahi-histeroskopi',
  '/blog/kadin-kisirligi-ve-tup-bebek-tedavisinin-onemi': '/kadin-infertilitesi',
  '/blog/kadinlarda-yumurtalik-rezervi-ve-onemi': '/makaleler/kac-yumurta-gerekir',
  '/blog/kisirlik-belirtisi-endometriozis-cikolata-kisti-nedir': '/makaleler/endometrioma',
  '/blog/kisirlik-cozumsuz-degildir5-yazi-dizisi-asilama': '/makaleler/iui-nedir',
  '/blog/kisirlik-cozumsuz-degildir6-yazi-dizisi-mikroenjeksiyon': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/blog/kisirlik-psikolojisi': '/psikolojik-destek',
  '/blog/kisirlikta-naturel-siklusta-mikroenjeksiyon-icsi': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/blog/kisirlikta-yeni-umut-rahim-dokusu-nakli': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/blog/laparoskopi-nedir': '/makaleler/endoskopik-cerrahi-histeroskopi',
  '/blog/mikroenjeksiyon-bebekleri-ve-anomaliler': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/blog/mikroenjeksiyon-icsi-herkes-icin-uygun-mudur': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/blog/mol-gebelik-uzum-gebelik': '/makaleler/dusuk-sonrasi-hamilelik-bekleme-suresi#istisnalar',
  '/blog/opk-ve ivf': '/makaleler/opk-ve-ivf',
  '/blog/polip-nedir-kisirliga-yol-acar-mi': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/preimplantasyon-genetik-tani-nedir': '/pgt-merkezi',
  '/blog/rahmin-ters-durmasi-kisirliga-neden-olmaz-retrovert-uterus': '/kadin-infertilitesi',
  '/blog/tup-bebek-efsaneler-ve-gercekler': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/blog/tup-bebek-oncesi-histeroskopi-laparoskopi-basariyi-artirir-mi': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/tup-bebek-sureci-adim-adim-rehber': '/makaleler/tup-bebek-sureci-rehber',
  '/blog/tup-bebek-tedavisine-hazirlik-asamasi-yazi-dizisi-2': '/makaleler/tup-bebek-sureci-rehber',
  '/blog/tup-bebek-tedavisine-hazirlik-asamasi-yazi-dizisi-3': '/makaleler/tup-bebek-sureci-rehber',
  '/blog/tup-bebek-tedavisine-hazirlik-asamasi-yazi-dizisi-4': '/makaleler/tup-bebek-sureci-rehber',
  '/blog/yas-dogurganlik-ve-kisirlik': '/yas-ve-fertilite',
  '/blog/yumurtalik-kistleri-dogurganligi-etkiler-mi': '/makaleler/yumurtalik-kistleri-dogurganlik',
  '/blog/yumurtaliklarin-uyarilmasinda-kullanilan-ilaclar-ve-kanser': '/makaleler/ivf-protokolleri',
};

export function normalizeInternalPath(value) {
  if (!value || typeof value !== 'string' || !value.startsWith('/')) {
    return value;
  }

  const source = splitPathQueryHash(value);
  const normalizedPath = source.path.replace(/\/+$/, '') || '/';
  const loweredPath = normalizedPath.toLowerCase();
  const target = routeAliases[normalizedPath] || routeAliases[loweredPath];

  return target ? normalizeAliasTarget(target, source) : value;
}

function splitPathQueryHash(value) {
  const hashIndex = value.indexOf('#');
  const beforeHash = hashIndex >= 0 ? value.slice(0, hashIndex) : value;
  const hash = hashIndex >= 0 ? value.slice(hashIndex) : '';
  const queryIndex = beforeHash.indexOf('?');
  const path = queryIndex >= 0 ? beforeHash.slice(0, queryIndex) : beforeHash;
  const query = queryIndex >= 0 ? beforeHash.slice(queryIndex) : '';

  return { path, query, hash };
}

function normalizeAliasTarget(target, source) {
  const targetParts = splitPathQueryHash(target);
  const path = targetParts.path;
  const query = source.query || targetParts.query;
  const hash = targetParts.hash || source.hash;

  if (path === '/' || path.endsWith('/') || /\.[a-z0-9]+$/iu.test(path)) {
    return `${path}${query}${hash}`;
  }

  return `${path}/${query}${hash}`;
}
