export const routeAliases = {
  '/ar/blog/azoospermia-and-micro-tese': '/makaleler/azospermi-mikro-tese',
  '/ar/blog/bleeding-after-embryo-transfer': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/ar/blog/endometriosis-infertility-ivf-surgery-2025': '/makaleler/endometriozis-tup-bebek',
  '/ar/blog/vaginal-microbiome-ivf-success-lactobacillus-crispatus': '/makaleler/vajinal-mikrobiyom-fiv',
  '/ar/before-you-come': '/tani-sureci',
  '/ar/dr-senai-aksoy': '/hakkimizda',
  '/ar': '/',
  '/aciklanamayan-kisirlik': '/aciklanamayan-infertilite',
  '/about-us': '/hakkimizda',
  '/asilama': '/tedavi-yontemleri#iui',
  '/before-you-come': '/tani-sureci',
  '/baslarken': '/ivf-rehberi',
  '/blog/azoospermia-and-micro-tese': '/makaleler/azospermi-mikro-tese',
  '/blog/bleeding-after-embryo-transfer': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/can-preimplantation-genetic-testing-be-used-for-sex-selection': '/makaleler/pgt-cinsiyet-secimi',
  '/blog/candidates-for-hysteroscopy': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/care-after-embryo-transfer-with-ivf': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/chronic-endometritis-and-ivf': '/makaleler/endometriozis-tup-bebek',
  '/blog/decoding-the-beta-hcg-test-results-for-ivf-patients': '/makaleler/beta-hcg-testi',
  '/blog/discharge-itching-odor-yeast-infection-or-bacterial-vaginosis': '/makaleler/akinti-kasinti-koku',
  '/blog/embryo-transfer-ivf-treatment': '/makaleler/embriyo-transferi-gun-secimi',
  '/blog/endometrial-scratching-ivf': '/makaleler/endometriyal-scratching',
  '/blog/endometriosis-diagnosis-2025': '/makaleler/endometriozis-akilli-stratejiler',
  '/blog/elevating-ivf-journey-the-chic-guide': '/makaleler/tup-bebek-sureci-rehber',
  '/blog/exploring-the-role-of-female-infertility-in-ivf-treatment': '/kadin-infertilitesi',
  '/blog/frozen-embryo-transfer-endometrial-preparation-protocols-hrt-natural-hybrid': '/makaleler/taze-dondurulmus-transfer',
  '/blog/guide-complete-freezing-oocytes': '/makaleler/yumurta-dondurma-rehberi',
  '/blog/how-many-eggs-for-ivf-success': '/makaleler/kac-yumurta-gerekir',
  '/blog/hydrosalpinx-and-infertility': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/hysteroscopy-female-infertility-evidence-guide': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/isotretinoin-for-azoospermia': '/makaleler/izotretinoin-sperm',
  '/blog/ivf-as-an-option-for-women-with-ovulation-disorders': '/makaleler/opk-ve-ivf',
  '/blog/ivf-protocols-medications': '/makaleler/ivf-protokolleri',
  '/blog/in-vitro-fertilization-treatment-and-polycystic-ovary-syndrome': '/makaleler/opk-ve-ivf',
  '/blog/male-infertility-supplements-comprehensive-guide': '/makaleler/erkek-dogurganlik-besin-takviyeleri',
  '/blog/ovarian-prp': '/makaleler/over-prp',
  '/blog/pcos-and-ivf': '/makaleler/opk-ve-ivf',
  '/blog/preimplantation-genetic-diagnosis-of-monogenic-diseases': '/makaleler/pgt-m',
  '/blog/research-into-the-relationship-between-hyperprolactinemia-and-milk-secretion': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/the-use-of-frozen-embryos-in-ivf-treatment': '/makaleler/taze-dondurulmus-transfer',
  '/blog/understanding-the-reproductive-potential-of-ivf': '/makaleler/tup-bebek-nedir',
  '/blog/understanding-unexplained-infertility-guide-for-couples': '/makaleler/aciklanamayan-infertilite',
  '/blog/understanding-uterine-fibroids-and-infertility': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/unraveling-the-complexities-of-hyperprolactinemia': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/dogurganligin-korunmasi': '/fertilite-koruma',
  '/dr-senai-aksoy': '/hakkimizda',
  '/dr-senai-aksoy/undefined/dr-senai-aksoy': '/hakkimizda',
  '/embriyo-dondurma': '/fertilite-koruma',
  '/hizmetler': '/tedavi-yontemleri',
  '/health-visa': '/tani-sureci',
  '/erkegin-degerlendirilmesi': '/erkek-infertilitesi',
  '/fr': '/',
  '/fr/blog/adenomyose-et-infertilite': '/makaleler/hormonal-tedavi-adenomyozis',
  '/fr/blog/azoospermie-microtese': '/makaleler/azospermi-mikro-tese',
  '/fr/blog/echec-fiv-que-faire-dr-senai-aksoy': '/makaleler/basarisiz-denemeler',
  '/fr/blog/fiv-et-limite-dage-le-point-de-vue-dun-medecin': '/yas-ve-fertilite',
  '/fr/blog/fiv-turquie-securite-qualite-couts': '/makaleler/iyi-tup-bebek-merkezi',
  '/fr/blog/frozen-embryo-transfer-endometrial-preparation-protocols-hrt-natural-hybrid': '/makaleler/taze-dondurulmus-transfer',
  '/fr/blog/grossesse-naturelle-apres-fiv-surprise-fertilite': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/fr/blog/diagnostic-preimplantatoire-des-maladies-monogeniques': '/makaleler/pgt-m',
  '/fr/blog/diagnostic-preimplantatoire-et-selection-du-sexe': '/makaleler/pgt-cinsiyet-secimi',
  '/fr/blog/embryoglue-fiv-efficacite-taux-reussite': '/makaleler/embryoglue-faydalari',
  '/fr/blog/endometrite-chronique-et-fiv': '/makaleler/endometriozis-tup-bebek',
  '/fr/blog/guide-complet-congelation-ovocytes': '/makaleler/yumurta-dondurma-rehberi',
  '/fr/blog/hydrosalpinx-et-infertilite': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/fr/blog/hyperprolactinemie-et-infertilite': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/fr/blog/hysteroscopie-avant-fiv-necessite-recommandations': '/makaleler/ivf-oncesi-histeroskopi',
  '/fr/blog/comprendre-infertilite-en-fiv': '/makaleler/tup-bebek-nedir',
  '/fr/blog/infertilite-inexpliquee': '/makaleler/aciklanamayan-infertilite',
  '/fr/blog/isotretinoine-restauration-spermatogenese-noa': '/makaleler/izotretinoin-sperm',
  '/fr/blog/le-prp-ovarien': '/makaleler/over-prp',
  '/fr/blog/microbiote-vaginal-et-succes-fiv': '/makaleler/vajinal-mikrobiyom-fiv',
  '/fr/blog/moment-optimal-pour-le-transfert-embryons': '/makaleler/embriyo-transferi-gun-secimi',
  '/fr/blog/myomectomie-coelioscopie-limites-fertilite': '/makaleler/miyom-ameliyati',
  '/fr/blog/pcos-et-fiv': '/makaleler/opk-ve-ivf',
  '/fr/blog/risques-caches-des-grossesses-gemellaires-en-fiv': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/fr/blog/soins-post-transfert-embryons': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/fr/blog/treatment-pain-associated-endometriosis': '/makaleler/endometriozis-akilli-stratejiler',
  '/fr/blog/traitements-chirurgicaux-douleur-endometriose': '/makaleler/endometriozis-akilli-stratejiler',
  '/fr/blog/transfert-embryons-dans-le-traitement-de-la-fiv': '/makaleler/embriyo-transferi-gun-secimi',
  '/histeroskopi': '/makaleler/ivf-oncesi-histeroskopi',
  '/laparoskopi': '/endometriozis-adenomyozis',
  '/cost-of-ivf': '/sss',
  '/fr/cost-of-ivf': '/sss',
  '/kadinda-kisirlik-nedenleri': '/kadin-infertilitesi',
  '/kisirlik-nedenleri/aciklanamayan-kisirlik': '/aciklanamayan-infertilite',
  '/kvkk': '/gizlilik-politikasi',
  '/makaleler/dondurulmus-embriyo-transferi': '/makaleler/taze-dondurulmus-transfer',
  '/makaleler/erkek-kisirligi-besin-takviyeleri': '/makaleler/erkek-dogurganlik-besin-takviyeleri',
  '/makaleler/hiperprolaktinemi-prolaktinom': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/makaleler/myomlar-ve-kisirlik': '/makaleler/miyomlar-ve-tup-bebek',
  '/makaleler/pkos-ve-tup-bebek': '/makaleler/opk-ve-ivf',
  '/policy': '/gizlilik-politikasi',
  '/services': '/tedavi-yontemleri',
  '/step-by-step-ivf-process': '/ivf-rehberi',
  '/treatment': '/tedavi-yontemleri',
  '/treatment/causes-and-diagnosis-of-infertility': '/tedavi-yontemleri',
  '/treatment/do-i-need-treatment': '/tedavi-yontemleri',
  '/treatment/embryo-freezing': '/makaleler/taze-dondurulmus-transfer',
  '/treatment/embryo-transfer': '/makaleler/embriyo-transferi-gun-secimi',
  '/treatment/egg-retrieval': '/tedavi-yontemleri',
  '/treatment/faq': '/sss',
  '/treatment/pre-ivf-testing': '/tani-sureci',
  '/treatment/preimplantation-genetic-diagnosis': '/pgt-merkezi',
  '/treatment/reasons-for-cancellation-of-treatment': '/tedavi-yontemleri',
  '/treatment/sperm-retrieval-in-azoospermic-subjects': '/makaleler/cerrahi-sperm-arama-tese',
  '/treatment/stimulation-of-the-ovaries': '/makaleler/ivf-protokolleri',
  '/sik-sorulan-sorular': '/sss',
  '/tedavi-sureci': '/tedavi-yontemleri',
  '/tedavi-sirasinda-karsilasilan-sorunlar': '/ivf-rehberi',
  '/tedaviler': '/tedavi-yontemleri',
  '/tedaviniz': '/ivf-rehberi',
  '/tesatese': '/makaleler/azospermi-mikro-tese',
  '/tup-bebek-asamalari': '/transfer-sureci',
  '/tup-bebek-basari-oranlari': '/basari-oranlari',
  '/tup-bebek-evraklari-ve-testleri': '/tani-sureci',
  '/tup-bebek-fiyatlari': '/sss',
  '/tup-bebek-tedavisinde-catlatma-ignesi': '/makaleler/ivf-protokolleri',
  '/tup-bebek-tedavisinde-nelere-dikkat-etmelisiniz': '/makaleler/tup-bebek-sureci-rehber',
  '/tup-bebek-tedavisinde-preimplantasyon-genetik-tani': '/pgt-merkezi',
  '/tup-bebek-ve-mikroenjeksiyon': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/tup-bebekte-ozel-uygulamalar': '/tedavi-yontemleri',
  '/videolar/mikroenjeksiyon-yontemi-hangi-durumlarda-uygulanir': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/videolar/rahim-ici-yapisikliklarinda-ofis-histeroskopi': '/makaleler/ivf-oncesi-histeroskopi',
  '/yasiniz-ve-kisirlik': '/yas-ve-fertilite',
  '/yumurtaliklarin-asiri-uyarilmasi': '/makaleler/ivf-protokolleri',
  '/yumurtlama-takibi': '/makaleler/yumurtlama-takibi',
  '/yazar': '/yayin-kurulu',
  '/blog/akinti-kasinti-koku-mantar-mi-bakteriyel-vajinoz-mu': '/makaleler/akinti-kasinti-koku',
  '/blog/tup-bebek-bagisiklik-tedavileri-ve-riskler': '/makaleler/bagisiklik-tedavileri',
  '/blog/ivf-oncesi-histeroskopi-rif-hastalari': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/embryoscope-yapay-zeka-embriyo-secimi': '/makaleler/embryoscope-yapay-zeka',
  '/blog/yumurta-dondurma-kac-tanesi-gerekli-yas-gruplari': '/makaleler/yumurta-dondurma-rehberi',
  '/blog/izotretinoin-noa-sperm-uretimi': '/makaleler/izotretinoin-sperm',
  '/blog/embriyo-tup-bebek-laboratuvar-raporu-yorumlama': '/makaleler/laboratuvar-raporu-yorumlama',
  '/blog/istanbul-tup-bebek-doktoru-merkezi-secimi-rehberi': '/makaleler/istanbul-tup-bebek-doktoru',
  '/blog/akraba-evliligi-neden-tehlikelidir': '/makaleler/akraba-evliligi',
  '/blog/embriyo-transferi-kacinci-gunde-yapilmalidir': '/makaleler/embriyo-transferi-gun-secimi',
  '/blog/dondurulmus-embriyo-transferi-protokolleri-karsilastirma': '/makaleler/taze-dondurulmus-transfer',
  '/blog/vajinal-mikrobiyom-fiv-basarisi': '/makaleler/vajinal-mikrobiyom-fiv',
  '/blog/endometriozis-ve-tup-bebek-tedavisi': '/makaleler/endometriozis-tup-bebek',
  '/blog/endometriozis-kisirlik-iliskisi': '/makaleler/endometriozis-tup-bebek',
  '/blog/kisirlik-ve-endometriozis-icin-akilli-stratejiler': '/makaleler/endometriozis-akilli-stratejiler',
  '/blog/azospermi-mikro-tese-ikinci-deneme': '/makaleler/azospermi-mikro-tese',
  '/blog/azospermi-nedir': '/makaleler/cerrahi-sperm-arama-tese',
  '/blog/tup-bebekte-basarili-sonuc-icin-kac-yumurta-gerekir': '/makaleler/kac-yumurta-gerekir',
  '/blog/yumurtlama-takibi-ve-iliski-planlamasi-nedir': '/makaleler/yumurtlama-takibi',
  '/blog/saglikli-bir-cinsel-hayat-icin-ne-yapmali': '/beslenme-yasam',
  '/blog/taze-dondurulmus-embriyo-transferi': '/makaleler/taze-dondurulmus-transfer',
  '/blog/miyom-ameliyati-ne-zaman-gerekir': '/makaleler/miyom-ameliyati',
  '/blog/miyomlarin-gebelik-uzerinde-etkileri-nelerdir': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/myomektomi-myom-nedir': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/laparoskopik-myomektomi': '/makaleler/miyom-ameliyati',
  '/blog/dusuk-amh': '/makaleler/dusuk-amh-hamilelik',
  '/blog/zayif-yumurtalik-rezervi-ve-tup-bebek-tedavisi': '/makaleler/dusuk-amh-hamilelik',
  '/blog/prematur-ovarian-yetmezlik-kisirlik-nedeni': '/makaleler/dusuk-amh-hamilelik',
  '/blog/erken-yumurtalik-yetmezligi-kisirlik-nedeni': '/makaleler/dusuk-amh-hamilelik',
  '/blog/erken-menopoz-nedir': '/makaleler/dusuk-amh-hamilelik',
  '/blog/fiv-basarisizligi-sonrasi-ne-yapmali-dr-senai-aksoy': '/makaleler/basarisiz-denemeler',
  '/blog/tekrarlayan-dusuklerin-nedenleri': '/makaleler/basarisiz-denemeler',
  '/blog/tup-bebek-tedavisinde-tekrarlayan-basarisizliklar': '/makaleler/basarisiz-denemeler',
  '/blog/luteal-faz-defekti-kisirlik-nedeni': '/makaleler/basarisiz-denemeler',
  '/blog/ivf-protokolleri-istanbul': '/makaleler/ivf-protokolleri',
  '/blog/hiperprolaktinemi-ve-kisirlik': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/hiperprolaktinemi-ve-prolaktinomu-anlamak': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/gogusten-sivi-gelmesi-galaktore-nedir': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/asiri-sut-uretimi-hiperprolaktinemi': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/myomlar-ve-kisirlik': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/kimyasal-gebelik': '/makaleler/kimyasal-gebelik',
  '/blog/bos-gebelik-nedir': '/makaleler/kimyasal-gebelik',
  '/blog/hamile-kalamiyorsaniz-nedeni-hidrosalpinks-olabilir': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/hidrosalpinks-ve-tuplerin-alinmasi': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/hydrosalpinx-ve-kisirlik': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/pelvik-inflamatuar-hastalik-pid-kisirlik-nedeni-olabilir': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/tuboovarian-abse-toa': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/embriyo-tutunmasi-implantasyon-1-rahime-ait-problemler': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/embriyo-tutunmasi-implantasyon-2-embriyoya-ait-problemler': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/embriyo-tutunmasi-implantasyon-3-tup-bebek-asamalarinda-yapilabilecekler': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/tup-bebek-ve-embriyo-transferi-sonrasi-bakim': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/tup-bebek-tedavisinde-luteal-faz-kanamalari': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/tup-bebek-tedavisinde-blastokist-transferi-nedir': '/makaleler/embriyo-transferi-gun-secimi',
  '/blog/kisirlik-cozumsuz-degildir1-yazi-dizisi-kadinda-kisirlik-nedenleri': '/kadin-infertilitesi',
  '/blog/kisirlik-cozumsuz-degildir2-yazi-dizisi-kadinda-tup-bebek-tedavisi': '/makaleler/tup-bebek-nedir',
  '/blog/kisirlik-cozumsuz-degildir2-yazi-dizisi-erkekte-baslica-kisirlik-nedenleri': '/erkek-infertilitesi',
  '/blog/kisirlik-cozumsuz-degildir4-yazi-dizisi-azospermi-cerrahi-sperm-arama-teknikleri': '/makaleler/cerrahi-sperm-arama-tese',
  '/blog/erkekte-kisirlik-tedavisinde-cerrahi-sperm-arama-tesa-tese': '/makaleler/cerrahi-sperm-arama-tese',
  '/blog/kisirlik-cozumsuz-degildir3-yazi-dizisi-erkekte-kisirlik-nasil-degerlendirilir': '/erkek-infertilitesi',
  '/blog/erkekte-kisirlik-nedeni-varikosel-nedir': '/erkek-infertilitesi',
  '/blog/tup-bebek-tedavisi-esnasinda-semen-analizi-nedir': '/erkek-infertilitesi',
  '/blog/erkek-dogurganligini-artiran-besin-takviyeleri': '/makaleler/erkek-dogurganlik-besin-takviyeleri',
  '/blog/tup-bebek-artik-pek-cok-durumda-oncelikli-tedavi-yontemi': '/makaleler/tup-bebek-nedir',
  '/blog/tup-bebek-nedir-kimlere-uygulanir': '/makaleler/tup-bebek-nedir',
  '/blog/pek-cok-kisir-ciftin-hayatini-degistiren-mucize-tup-bebek': '/makaleler/tup-bebek-nedir',
  '/blog/tup-bebek-tedavisinde-tartismali-teknik-kokultur-yapay-rahim': '/makaleler/tup-bebek-nedir',
  '/blog/tup-bebek-tedavisine-hazirlik-asamasi-yazi-dizisi-1': '/makaleler/tup-bebek-sureci-rehber',
  '/blog/iyi-tup-bebek-merkezi-nasil-anlasilir': '/makaleler/iyi-tup-bebek-merkezi',
  '/blog/mikroenjeksiyonda-imsi-nedir': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/blog/mikroenjeksiyon-icsi-nedir-kimlere-uygulanir': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/blog/beta-hcg-test-sonuclari': '/makaleler/beta-hcg-testi',
  '/blog/yumurtalik-kistleri-dermoid-kist': '/makaleler/yumurtalik-kistleri-dogurganlik',
  '/blog/over-prp': '/makaleler/over-prp',
  '/blog/pgt-m': '/makaleler/pgt-m',
  '/blog/preimplantasyon-genetik-testi-ve-cinsiyet-secimi': '/makaleler/pgt-cinsiyet-secimi',
  '/blog/embriyoda-genetik-tani-preimplantasyon-genetik-tani': '/pgt-merkezi',
  '/blog/embryoglue-embriyo-yapistiricisi-faydalari': '/makaleler/embryoglue-faydalari',
  '/blog/pkos-ve-tup-bebek': '/makaleler/opk-ve-ivf',
  '/blog/polikistik-over-sendromu-nedenleri-ve-tedavisi': '/makaleler/opk-ve-ivf',
  '/blog/adet-duzensizligi-ve-polikistik-over-sendromu-pkos': '/makaleler/adet-duzensizligi-pcos',
  '/blog/adet-oncesi-sendromu': '/makaleler/adet-duzensizligi-pcos',
  '/blog/adet-gorememe-amenore': '/makaleler/adet-gorememe',
  '/blog/alkol-ve-fertilite': '/makaleler/alkol-ve-fertilite',
  '/blog/hormonal-tedavilerle-adenomyozis': '/makaleler/hormonal-tedavi-adenomyozis',
  '/blog/hysteroscopic-cytoreductive-surgery-for-adenomyosis': '/makaleler/hormonal-tedavi-adenomyozis',
  '/blog/asherman-sendromu-rahim-ici-yapisiklik': '/makaleler/asherman-sendromu',
  '/blog/embriyo-dondurma-teknigi-vitrifikasyon': '/makaleler/taze-dondurulmus-transfer',
  '/blog/assisted-hatching-destekli-yuvalama-nedir': '/makaleler/ivf-protokolleri',
  '/blog/tup-bebek-tedavisinde-yumurta-toplamanin-gecikmesi': '/makaleler/ivf-protokolleri',
  '/blog/yumurta-toplamada-genel-anestezi-mi-sedasyon-mu': '/makaleler/ivf-protokolleri',
  '/blog/tup-bebek-tedavisinde-yumurtalik-hiperstimulasyon-sendromu-ohss': '/makaleler/ivf-protokolleri',
  '/blog/tup-bebek-tedavisinde-bos-folikul-sendromu': '/makaleler/ivf-protokolleri',
  '/blog/hlag-ne-kadar-yararli': '/makaleler/ivf-protokolleri',
  '/blog/ofis-histeroskopi-nedir': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/intrauterin-inseminasyon-iui-nedir': '/makaleler/iui-nedir',
  '/blog/immunological-treatments-ivf-implantation-failure': '/makaleler/bagisiklik-tedavileri',
  '/blog/yumurtalik-donmesi-over-torsiyonu': '/makaleler/endometrioma',
  '/blog/cikolata-kisti-endometriozis-ameliyati-yumurtalik-veya-rahmin-alinmasini-gerektirmez': '/makaleler/endometrioma',
  '/blog/klamidya-kisirliga-neden-olabilir': '/makaleler/akinti-kasinti-koku',
  '/blog/vajinit-vajinal-enfeksiyon-ve-vajinal-akinti': '/makaleler/akinti-kasinti-koku',
  '/blog/bel-sogukluguna-kadinlar-da-yakalanabilir': '/makaleler/akinti-kasinti-koku',
  '/blog/hamilelikte-sik-gorulen-vajinal-enfeksiyonlar': '/makaleler/akinti-kasinti-koku',
  '/blog/tup-bebek-ve-kisirlik-hakkinda-yanlis-bilinen-gercekler': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/blog/tup-bebekte-kullanilan-kanita-dayali-olmayan-tedaviler': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/blog/kanser-tedavisine-bagli-kisirlik-ve-dogurganligin-korunmasi': '/makaleler/kanser-ve-fertilite',
  '/blog/stres-tup-bebek-basarisini-etkiler-mi': '/psikolojik-destek',
  '/blog/stres-ve-kisirlik': '/psikolojik-destek',
  '/blog/sigara-ve-kisirlik': '/beslenme-yasam',
  '/blog/sigaranin-dogurganlik-ve-kisirlik-uzerinde-etkisi': '/beslenme-yasam',
  '/blog/dogurganligi-arttirmanin-10-yolu': '/beslenme-yasam',
  '/blog/gebelikte-cinsel-yasam': '/beslenme-yasam',
  '/blog/hamilelik-ve-flor': '/beslenme-yasam',
  '/blog/hamilelik-ve-alkol': '/beslenme-yasam',
  '/blog/hamilelerde-tiroid-hastaliklari': '/hormon-paneli',
  '/blog/anne-karninda-tarama-testleri': '/genetik-testler',
  '/blog/ilacli-rahim-filmi-hsg-nedir': '/tani-sureci',
  '/blog/dogumsal-rahim-anomalileri-konjenital-uterin-anomalileri': '/kadin-infertilitesi',
  '/blog/dogustan-rahmin-olmamasi-mullerian-agnenezi-rokitansky-kuster-hauser-mayer-sendromu-rkm': '/kadin-infertilitesi',
  '/blog/kisirlik-infertilite-nedir-nedenleri-nelerdir': '/kadin-infertilitesi',
  '/blog/embriyo-transferi-kacinci-': '/makaleler/embriyo-transferi-gun-secimi',
  '/blog/sayfa/*': '/makaleler',
};

export function normalizeInternalPath(value) {
  if (!value || typeof value !== 'string' || !value.startsWith('/')) {
    return value;
  }

  const source = splitPathQueryHash(value);
  const normalizedPath = source.path.replace(/\/+$/, '') || '/';
  const loweredPath = normalizedPath.toLowerCase();
  const target = routeAliases[normalizedPath] || routeAliases[loweredPath];

  return target ? normalizeAliasTarget(target, source) : value;
}

function splitPathQueryHash(value) {
  const hashIndex = value.indexOf('#');
  const beforeHash = hashIndex >= 0 ? value.slice(0, hashIndex) : value;
  const hash = hashIndex >= 0 ? value.slice(hashIndex) : '';
  const queryIndex = beforeHash.indexOf('?');
  const path = queryIndex >= 0 ? beforeHash.slice(0, queryIndex) : beforeHash;
  const query = queryIndex >= 0 ? beforeHash.slice(queryIndex) : '';

  return { path, query, hash };
}

function normalizeAliasTarget(target, source) {
  const targetParts = splitPathQueryHash(target);
  const path = targetParts.path;
  const query = source.query || targetParts.query;
  const hash = targetParts.hash || source.hash;

  if (path === '/' || path.endsWith('/') || /\.[a-z0-9]+$/iu.test(path)) {
    return `${path}${query}${hash}`;
  }

  return `${path}/${query}${hash}`;
}
