export const routeAliases = {
  '/ar/blog/azoospermia-and-micro-tese': '/makaleler/azospermi-mikro-tese',
  '/ar/blog/bleeding-after-embryo-transfer': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/ar/blog/endometriosis-infertility-ivf-surgery-2025': '/makaleler/endometriozis-tup-bebek',
  '/ar/blog/vaginal-microbiome-ivf-success-lactobacillus-crispatus': '/makaleler/vajinal-mikrobiyom-fiv',
  '/ar/before-you-come': '/tani-sureci',
  '/ar/dr-senai-aksoy': '/hakkimizda',
  '/aciklanamayan-kisirlik': '/aciklanamayan-infertilite',
  '/about-us': '/hakkimizda',
  '/asilama': '/tedavi-yontemleri#iui',
  '/before-you-come': '/tani-sureci',
  '/blog/azoospermia-and-micro-tese': '/makaleler/azospermi-mikro-tese',
  '/blog/bleeding-after-embryo-transfer': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/can-preimplantation-genetic-testing-be-used-for-sex-selection': '/makaleler/pgt-cinsiyet-secimi',
  '/blog/candidates-for-hysteroscopy': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/care-after-embryo-transfer-with-ivf': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/blog/chronic-endometritis-and-ivf': '/makaleler/endometriozis-tup-bebek',
  '/blog/decoding-the-beta-hcg-test-results-for-ivf-patients': '/makaleler/beta-hcg-testi',
  '/blog/discharge-itching-odor-yeast-infection-or-bacterial-vaginosis': '/makaleler/akinti-kasinti-koku',
  '/blog/embryo-transfer-ivf-treatment': '/makaleler/embriyo-transferi-gun-secimi',
  '/blog/endometrial-scratching-ivf': '/makaleler/endometriyal-scratching',
  '/blog/endometriosis-diagnosis-2025': '/makaleler/endometriozis-akilli-stratejiler',
  '/blog/elevating-ivf-journey-the-chic-guide': '/makaleler/tup-bebek-sureci-rehber',
  '/blog/exploring-the-role-of-female-infertility-in-ivf-treatment': '/kadin-infertilitesi',
  '/blog/frozen-embryo-transfer-endometrial-preparation-protocols-hrt-natural-hybrid': '/makaleler/taze-dondurulmus-transfer',
  '/blog/guide-complete-freezing-oocytes': '/makaleler/yumurta-dondurma-rehberi',
  '/blog/how-many-eggs-for-ivf-success': '/makaleler/kac-yumurta-gerekir',
  '/blog/hydrosalpinx-and-infertility': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/blog/hysteroscopy-female-infertility-evidence-guide': '/makaleler/ivf-oncesi-histeroskopi',
  '/blog/isotretinoin-for-azoospermia': '/makaleler/izotretinoin-sperm',
  '/blog/ivf-as-an-option-for-women-with-ovulation-disorders': '/makaleler/opk-ve-ivf',
  '/blog/ivf-protocols-medications': '/makaleler/ivf-protokolleri',
  '/blog/in-vitro-fertilization-treatment-and-polycystic-ovary-syndrome': '/makaleler/opk-ve-ivf',
  '/blog/male-infertility-supplements-comprehensive-guide': '/makaleler/erkek-dogurganlik-besin-takviyeleri',
  '/blog/ovarian-prp': '/makaleler/over-prp',
  '/blog/pcos-and-ivf': '/makaleler/opk-ve-ivf',
  '/blog/preimplantation-genetic-diagnosis-of-monogenic-diseases': '/makaleler/pgt-m',
  '/blog/research-into-the-relationship-between-hyperprolactinemia-and-milk-secretion': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/blog/the-use-of-frozen-embryos-in-ivf-treatment': '/makaleler/taze-dondurulmus-transfer',
  '/blog/understanding-the-reproductive-potential-of-ivf': '/makaleler/tup-bebek-nedir',
  '/blog/understanding-unexplained-infertility-guide-for-couples': '/makaleler/aciklanamayan-infertilite',
  '/blog/understanding-uterine-fibroids-and-infertility': '/makaleler/miyomlar-ve-tup-bebek',
  '/blog/unraveling-the-complexities-of-hyperprolactinemia': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/dogurganligin-korunmasi': '/fertilite-koruma',
  '/dr-senai-aksoy': '/hakkimizda',
  '/embriyo-dondurma': '/fertilite-koruma',
  '/health-visa': '/tani-sureci',
  '/fr/blog/adenomyose-et-infertilite': '/makaleler/hormonal-tedavi-adenomyozis',
  '/fr/blog/azoospermie-microtese': '/makaleler/azospermi-mikro-tese',
  '/fr/blog/echec-fiv-que-faire-dr-senai-aksoy': '/makaleler/basarisiz-denemeler',
  '/fr/blog/fiv-et-limite-dage-le-point-de-vue-dun-medecin': '/yas-ve-fertilite',
  '/fr/blog/fiv-turquie-securite-qualite-couts': '/makaleler/iyi-tup-bebek-merkezi',
  '/fr/blog/frozen-embryo-transfer-endometrial-preparation-protocols-hrt-natural-hybrid': '/makaleler/taze-dondurulmus-transfer',
  '/fr/blog/grossesse-naturelle-apres-fiv-surprise-fertilite': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/fr/blog/diagnostic-preimplantatoire-des-maladies-monogeniques': '/makaleler/pgt-m',
  '/fr/blog/diagnostic-preimplantatoire-et-selection-du-sexe': '/makaleler/pgt-cinsiyet-secimi',
  '/fr/blog/embryoglue-fiv-efficacite-taux-reussite': '/makaleler/embryoglue-faydalari',
  '/fr/blog/endometrite-chronique-et-fiv': '/makaleler/endometriozis-tup-bebek',
  '/fr/blog/guide-complet-congelation-ovocytes': '/makaleler/yumurta-dondurma-rehberi',
  '/fr/blog/hydrosalpinx-et-infertilite': '/makaleler/hidrosalpinx-ve-kisirlik',
  '/fr/blog/hyperprolactinemie-et-infertilite': '/makaleler/hiperprolaktinemi-ve-kisirlik',
  '/fr/blog/hysteroscopie-avant-fiv-necessite-recommandations': '/makaleler/ivf-oncesi-histeroskopi',
  '/fr/blog/comprendre-infertilite-en-fiv': '/makaleler/tup-bebek-nedir',
  '/fr/blog/infertilite-inexpliquee': '/makaleler/aciklanamayan-infertilite',
  '/fr/blog/isotretinoine-restauration-spermatogenese-noa': '/makaleler/izotretinoin-sperm',
  '/fr/blog/le-prp-ovarien': '/makaleler/over-prp',
  '/fr/blog/microbiote-vaginal-et-succes-fiv': '/makaleler/vajinal-mikrobiyom-fiv',
  '/fr/blog/moment-optimal-pour-le-transfert-embryons': '/makaleler/embriyo-transferi-gun-secimi',
  '/fr/blog/myomectomie-coelioscopie-limites-fertilite': '/makaleler/miyom-ameliyati',
  '/fr/blog/pcos-et-fiv': '/makaleler/opk-ve-ivf',
  '/fr/blog/risques-caches-des-grossesses-gemellaires-en-fiv': '/makaleler/tup-bebek-yanlis-bilinenler',
  '/fr/blog/soins-post-transfert-embryons': '/makaleler/embriyo-transferi-sonrasi-bakim',
  '/fr/blog/treatment-pain-associated-endometriosis': '/makaleler/endometriozis-akilli-stratejiler',
  '/fr/blog/traitements-chirurgicaux-douleur-endometriose': '/makaleler/endometriozis-akilli-stratejiler',
  '/fr/blog/transfert-embryons-dans-le-traitement-de-la-fiv': '/makaleler/embriyo-transferi-gun-secimi',
  '/histeroskopi': '/makaleler/ivf-oncesi-histeroskopi',
  '/laparoskopi': '/endometriozis-adenomyozis',
  '/cost-of-ivf': '/sss',
  '/fr/cost-of-ivf': '/sss',
  '/kvkk': '/gizlilik-politikasi',
  '/policy': '/gizlilik-politikasi',
  '/step-by-step-ivf-process': '/ivf-rehberi',
  '/treatment/causes-and-diagnosis-of-infertility': '/tedavi-yontemleri',
  '/treatment/do-i-need-treatment': '/tedavi-yontemleri',
  '/treatment/embryo-freezing': '/makaleler/taze-dondurulmus-transfer',
  '/treatment/embryo-transfer': '/makaleler/embriyo-transferi-gun-secimi',
  '/treatment/egg-retrieval': '/tedavi-yontemleri',
  '/treatment/faq': '/sss',
  '/treatment/pre-ivf-testing': '/tani-sureci',
  '/treatment/preimplantation-genetic-diagnosis': '/pgt-merkezi',
  '/treatment/reasons-for-cancellation-of-treatment': '/tedavi-yontemleri',
  '/treatment/sperm-retrieval-in-azoospermic-subjects': '/makaleler/cerrahi-sperm-arama-tese',
  '/treatment/stimulation-of-the-ovaries': '/makaleler/ivf-protokolleri',
  '/sik-sorulan-sorular': '/sss',
  '/tedavi-sureci': '/tedavi-yontemleri',
  '/tedaviler': '/tedavi-yontemleri',
  '/tesatese': '/makaleler/azospermi-mikro-tese',
  '/tup-bebek-asamalari': '/transfer-sureci',
  '/tup-bebek-basari-oranlari': '/basari-oranlari',
  '/tup-bebek-fiyatlari': '/sss#maliyet-sgk',
  '/tup-bebek-tedavisinde-catlatma-ignesi': '/makaleler/ivf-protokolleri',
  '/tup-bebek-tedavisinde-nelere-dikkat-etmelisiniz': '/makaleler/tup-bebek-sureci-rehber',
  '/tup-bebek-tedavisinde-preimplantasyon-genetik-tani': '/pgt-merkezi',
  '/tup-bebek-ve-mikroenjeksiyon': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/videolar/mikroenjeksiyon-yontemi-hangi-durumlarda-uygulanir': '/makaleler/mikroenjeksiyon-icsi-nedir',
  '/videolar/rahim-ici-yapisikliklarinda-ofis-histeroskopi': '/makaleler/ivf-oncesi-histeroskopi',
  '/yasiniz-ve-kisirlik': '/yas-ve-fertilite',
  '/yumurtaliklarin-asiri-uyarilmasi': '/makaleler/ivf-protokolleri',
  '/yumurtlama-takibi': '/makaleler/yumurtlama-takibi',
};

export function normalizeInternalPath(value) {
  if (!value || typeof value !== 'string' || !value.startsWith('/')) {
    return value;
  }

  const hashIndex = value.indexOf('#');
  const queryIndex = value.indexOf('?');
  const suffixIndex = [hashIndex, queryIndex].filter((index) => index >= 0).sort((a, b) => a - b)[0];
  const path = suffixIndex >= 0 ? value.slice(0, suffixIndex) : value;
  const suffix = suffixIndex >= 0 ? value.slice(suffixIndex) : '';
  const normalizedPath = path.replace(/\/+$/, '') || '/';
  const loweredPath = normalizedPath.toLowerCase();
  const target = routeAliases[normalizedPath] || routeAliases[loweredPath];

  return target ? `${target}${suffix}` : value;
}
